# Generated by Django 5.1.8 on 2025-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteralert',
            name='source_url',
            field=models.URLField(default='https://eonet.gsfc.nasa.gov/'),
            preserve_default=False,
        ),
    ]
