# Generated by Django 5.1.8 on 2025-04-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_disasteralert_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteralert',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
