# Generated by Django 5.1.8 on 2025-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_disasteralert_description_disasteralert_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='alert_type',
            field=models.CharField(choices=[('Wildfires', 'Wildfires'), ('Severe Storms', 'Severe Storms'), ('Volcanoes', 'Volcanoes'), ('Floods', 'Floods'), ('Earthquakes', 'Earthquakes'), ('Landslides', 'Landslides'), ('Snow', 'Snow'), ('Temperature Extremes', 'Temperature Extremes'), ('Drought', 'Drought'), ('Dust and Haze', 'Dust and Haze'), ('Icebergs', 'Icebergs')], default='Earthquake', max_length=50),
        ),
    ]
