# Generated by Django 5.1.8 on 2025-04-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alter_userpreference_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='alert_type',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='alert_types',
            field=models.ManyToManyField(blank=True, to='alerts.alerttype'),
        ),
    ]
