# Generated by Django 5.1.8 on 2025-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0006_alerttype_remove_userpreference_alert_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='alert_types',
            field=models.ManyToManyField(blank=True, related_name='user_preferences', to='alerts.alerttype'),
        ),
    ]
